# 1. Use "db" instead of "localhost" because we are inside Docker
# 2. Use "consultlink" to match your POSTGRES_DB name
spring.datasource.url=jdbc:postgresql://db:5432/consultlink
spring.datasource.username=postgres
spring.datasource.password=password

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# This helps Spring wait a bit longer for the DB to wake up
spring.datasource.hikari.initialization-fail-timeout=0

# Spring AI Configuration
# This maps your Groq key to the OpenAI property Spring is looking for
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

#spring.ai.google.genai.api-key=${GEMINI_API_KEY}
#spring.ai.google.genai.model=
#spring.ai.google.genai.enabled=true
# Force stable API and bypass beta propagation issues
# This overrides the library's default 'v1beta' path
#spring.ai.google.genai.base-url=https://generativelanguage.googleapis.com/v1
